ALTER TABLE `sys_file` ADD COLUMN `create_id` int DEFAULT NULL COMMENT '创建人';
ALTER TABLE `sys_file` ADD COLUMN `ext` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '扩展名';
ALTER TABLE `sys_file` ADD COLUMN `from_type` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '来源（上传、导入、导出）';


INSERT INTO `sys_menu` (`id`, `pid`, `path`, `name`, `title`, `icon`, `component`, `redirect`, `sort`, `deep`, `menu_type_cd`, `permissions`, `is_hidden`, `has_children`, `is_link`, `is_full`, `is_affix`, `is_keep_alive`, `create_time`, `update_time`, `create_id`, `update_id`, `del_flag`, `delete_id`, `delete_time`, `use_data_scope`) VALUES ('92063c881c884298a779de3eb506cafc', '88b2e5def2ff474fa8bf3537d4a2fe5b', '/system/FileMange', 'SysFileView', '文件记录', 'Files', '/system/FileMange/index', '', 900, 2, '1002002', 'sys.file.query_table', 'F', 'T', 'F', 'F', 'F', 'F', '2024-09-29 16:35:20', '2024-09-29 16:39:34', '', '1', 'F', NULL, NULL, 'F');
INSERT INTO `sys_dict_type` (`id`, `type_name`, `type_code`, `is_lock`, `is_show`, `del_flag`, `remark`, `create_time`, `update_time`, `delete_time`, `create_id`, `update_id`, `delete_id`, `type`) VALUES (1008, '文件数据来源', 'file_source_type', 'F', 'T', 'F', '文件数据来源', '2024-09-29 16:42:12', '2024-09-29 16:42:11', NULL, NULL, NULL, NULL, 'system');

INSERT INTO `sys_dict` (`id`, `sys_dict_type_id`, `code_name`, `alias`, `sort`, `callback_show_style`, `remark`, `is_lock`, `is_show`, `del_flag`, `create_time`, `update_time`, `delete_time`, `create_id`, `update_id`, `delete_id`) VALUES (1008001, 1008, '上传', '', 1, 'primary', '', 'F', 'T', 'F', '2024-09-29 16:44:28', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `sys_dict` (`id`, `sys_dict_type_id`, `code_name`, `alias`, `sort`, `callback_show_style`, `remark`, `is_lock`, `is_show`, `del_flag`, `create_time`, `update_time`, `delete_time`, `create_id`, `update_id`, `delete_id`) VALUES (1008002, 1008, '下载', '', 2, 'primary', '', 'F', 'T', 'F', '2024-09-29 16:45:12', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `sys_dict` (`id`, `sys_dict_type_id`, `code_name`, `alias`, `sort`, `callback_show_style`, `remark`, `is_lock`, `is_show`, `del_flag`, `create_time`, `update_time`, `delete_time`, `create_id`, `update_id`, `delete_id`) VALUES (1008003, 1008, '导入', '', 3, 'primary', '', 'F', 'T', 'F', '2024-09-29 16:45:19', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `sys_dict` (`id`, `sys_dict_type_id`, `code_name`, `alias`, `sort`, `callback_show_style`, `remark`, `is_lock`, `is_show`, `del_flag`, `create_time`, `update_time`, `delete_time`, `create_id`, `update_id`, `delete_id`) VALUES (1008004, 1008, '导出', '', 4, 'primary', '', 'F', 'T', 'F', '2024-09-29 16:45:29', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `sys_dict` (`id`, `sys_dict_type_id`, `code_name`, `alias`, `sort`, `callback_show_style`, `remark`, `is_lock`, `is_show`, `del_flag`, `create_time`, `update_time`, `delete_time`, `create_id`, `update_id`, `delete_id`) VALUES (1008005, 1008, '生成', '', 5, 'primary', '', 'F', 'T', 'F', '2024-09-29 16:45:35', NULL, NULL, NULL, NULL, NULL);

INSERT INTO `sys_role_menu` (`menu_id`, `role_id`) VALUES ( '92063c881c884298a779de3eb506cafc', 1);
